question_data = [
    {"category": "Animals",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A slug&rsquo;s blood is green.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A bear does NOT defecate during hibernation. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Rabbits are rodents.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A caterpillar has more muscles than humans do.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Cats have whiskers under their legs.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The Killer Whale is considered a type of dolphin.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Rabbits are carnivores.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The internet browser Firefox is named after the Red Panda.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
